# Generated by Django 4.2.5 on 2024-07-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0004_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
