# Generated by Django 4.2.5 on 2024-07-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0006_alter_productos_costo_alter_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock_optimo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
