# Generated by Django 4.2.5 on 2024-07-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0007_productos_stock_optimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
