# Generated by Django 4.2.5 on 2024-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0008_alter_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock_optimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
