# Generated by Django 4.2.5 on 2024-07-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0010_alter_productos_stock_optimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='promedio_ventas_dia',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
