# Generated by Django 4.2.5 on 2024-07-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0011_alter_productos_promedio_ventas_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='margen_de_ganancia',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
