# Generated by Django 4.2.5 on 2024-07-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0012_productos_margen_de_ganancia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='maxima_utilidad_unidad',
            new_name='utilidades_actuales',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='utilidades_esperadas',
            new_name='utilidades_anteriores',
        ),
    ]
